language: c
compiler:
  - gcc
  - clang
before_install:
    - sudo apt-get -qq update
    - sudo add-apt-repository -y ppa:maxmind/ppa
install:
    - sudo apt-get -qq install rake bison git gperf
    - sudo apt-get install -y libmaxminddb0 libmaxminddb-dev
before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-maxminddb-test/.travis_build_config.rb build_config.rb
script:
  - make all test
